### ISSUE TITLE
Package.json created by angular CLI generates "build": "ng build --prod" causing different behavior

### ISSUE THREAD

**Issue by mierasmade** [dsyer/spring-boot-angular#1]
In the example code the package.json uses "build": "ng build", however when following the steps in the readme, a slightly different package.json file gets created. Upon executing ./mvnw spring-boot:run the ng build --prod runs and some errors appear. 

Apart from that, excellent guide and very helpful 👍

**Comment by dsyer** [comment]
I think any differences you see between the described behaviour in the README and what happens in your own command line will be to do with Angular CLI differences. You can fix the version of Angular CLI to the one in the package.json if you want to smooth out the differences.
