### ISSUE TITLE
Could the guide  work on  MACOS

### ISSUE THREAD

**Issue by vincent-pli** [dsyer/spring-boot-angular#10]
I do everything strictly follow the guide, but I get this, my os is version 10.13.4(Hign Sierra)

> Angular CLI: 6.0.8
> Node: 8.11.2
> OS: darwin x64
> Angular: error
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router

**Comment by dsyer** [comment]
I just updated to Angular 6. Try again now.

**Comment by dsyer** [comment]
No feedback
