### ISSUE TITLE
Include Bootstrap CSS in `src\styles.css`

### ISSUE THREAD

**Issue by avi613** [dsyer/spring-boot-angular#11]
I'm just skimming through your project: [spring-boot-angular](https://github.com/dsyer/spring-boot-angular). I noticed that you indicate to include Bootstrap library like this:

```
"styles": [
    "styles.css",
    "../node_modules/bootstrap/dist/css/bootstrap.min.css"
  ],
```

I don't know about Bootstrap 3, but with Bootstrap 4 and angular 4 / 5, my experience is that this will only work in dev mode. Compilation will be a problem.

Importing `bootstrap.css` in `src\styles.css` like this 

```
@import "~bootstrap/dist/css/bootstrap.css";
```

will work in all cases.

I have posted [this stack](https://stackoverflow.com/questions/48593179/angular-5-with-bootstrap-4-not-working/49027017#49027017) about it.

**Comment by dsyer** [comment]
Fixed in 8b4c29f9. Thanks.
