### ISSUE TITLE
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by portatifparcacik** [dsyer/spring-boot-angular#12]
I tried `./mvnw generate-resources` and i got this error in Ubuntu 18.04,

> Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
> 	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
> 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:73)
> 	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:60)
> 	at org.apache.maven.wrapper.Installer.createDist(Installer.java:64)
> 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
> 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:50)
> Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
> 	at sun.security.validator.Validator.getInstance(Validator.java:179)
> 	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
> 	... 11 more
> Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
> 	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
> 	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
> 	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
> 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
> 	... 23 more

and I found this solution,

First remove conflicting packages:
`sudo apt-get remove --purge openjdk* java-common default-jdk`
`sudo apt-get autoremove --purge`
Check weather you successfully removed all related packages by:
`sudo update-alternatives --config java`
The system shall prompt you there is no Java available to config, otherwise this workaround fails.
Then reinstall required packages:
`sudo apt-get install openjdk-8-jdk`
[https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty/25188331#25188331](url)

then add JAVA_HOME. 

Open `/etc/environment` in any text editor like nano or gedit and add the following line:
`JAVA_HOME="/usr/lib/jvm/open-jdk"`
(java path could be different)
Use source to load the variables, by running this command:
`source /etc/environment`
Then check the variable, by running this command:
echo $JAVA_HOME
( https://askubuntu.com/questions/175514/how-to-set-java-home-for-java )

**Comment by dsyer** [comment]
Thanks for the update. Looks like you might be better off not using the JDK that is distributed with your OS in general. Try sdkman, for instance.
