### ISSUE TITLE
Angular routing 

### ISSUE THREAD

**Issue by avdhut1222** [dsyer/spring-boot-angular#13]
The angular routing doesn't work and is taken over by spring mappings. Try to navigate to login page by directly typing `localhost:8080/login` or refresh the browser at any page, it will give 404. I tried using the redirect `return "redirect:/" but it prints the string in the browser. Can you please help with this?

**Comment by salah3x** [comment]
A work around this would be using the HashLocationStrategy 
add `RouterModule.forRoot(routes, { useHash: true })` in import arrays in AppComponent
For more info see [the official docs](https://angular.io/guide/router#appendix-locationstrategy-and-browser-url-styles)

**Comment by dsyer** [comment]
Works for me (at least I don't see a 404). Maybe you had an older version?
