### ISSUE TITLE
Can't start the application

### ISSUE THREAD

**Issue by sarbull** [dsyer/spring-boot-angular#14]
```bash
$ cd spring-boot-angular
$ mvn clean install
```

![screen shot 2018-09-22 at 20 00 24](https://user-images.githubusercontent.com/1864112/45919691-36e8b580-bea2-11e8-99fe-424a35739b7b.png)

**Comment by Itachi-Uchiha78** [comment]
same here...

**Comment by Lempkin** [comment]
Same for me

**Comment by WiteCastle** [comment]
Yup, same here. I don't see any java code whatsoever. It's looking for the com.example.demo.DemoApplication file but it doesn't even exist.

**Comment by chrisinmtown** [comment]
I was going to open an issue that there are no nada zero Java files in this project but you all were way ahead of me.  @dsyer would you like a patch / PR to add this one file back using the version @WiteCastle suggests?

**Comment by dsyer** [comment]
See #18
