### ISSUE TITLE
It would be helpful to state explicitly "./npm init" in documentation

### ISSUE THREAD

**Issue by rjpruitt16** [dsyer/spring-boot-angular#16]
I spent so much time on this tutorial because npm was not running correctly. It would save time if you add the command "./npm init" after making npm executable to the documentation.

**Comment by dsyer** [comment]
It already says `./npm` everywhere I can see. Did you find another place?

**Comment by rjpruitt16** [comment]
./npm and ./npm init are not the same the thing. The code in the tutorial will not run unless initialized a npm folder.

**Comment by dsyer** [comment]
It works for me. Did you add the front-end plugin and re-run `mvn install` (or `mvn generate-resources` I think it says in the README)?

**Comment by rjpruitt16** [comment]
It has been month since I tried this tutorial. I just remember how frustrating it was trying to do this tutorial, and I wanted to help people avoid a trivial error. My machine is Mac OS, and I know I followed every step in the tutorial before coming to the realization I need to run npm init. If you are sure this error does not exist, have someone in your office try to follow this tutorial.

**Comment by dsyer** [comment]
I just tried it on someone else's Mac. Works for me. I reckon you missed a step.
