### ISSUE TITLE
Windows setup ??

### ISSUE THREAD

**Issue by MehdiAroui** [dsyer/spring-boot-angular#19]
Hello, thanks for your work, it would be great if there was a section about configuration under windows

**Comment by dsyer** [comment]
I don't use Windows much. I'd be happy to include a sentence of guidance if anyone knows a simple way to adapt the existing examples. I expect, but can't confirm, that the shell tools you get with Git on Windows would be enough to make it work almost verbatim.

**Comment by MehdiAroui** [comment]
I found a way, by copying **npm.cmd** file from 'node/node_modules/npm/bin/' to project root, and modify the path so it points on **npm-cli.js** of the local project.

the same for the file **ng.cmd**, just copy it from 'node_modules/angular/cli/bin/' to project root, and modify the path.
