### ISSUE TITLE
Info: ./ng e2e fails with Angular CLI 8.3.20 if delete favicon.ico

### ISSUE THREAD

**Issue by zorner** [dsyer/spring-boot-angular#22]
Info: ./ng e2e fails with Angular CLI 8.3.20 if delete favicon.ico

the guide need to say to remove test for the icon or not delete favicon.ico.

**Comment by dsyer** [comment]
Angular stopped supporting e2e tests. I think they happen in the normal "test" script now.

**Comment by mraible** [comment]
You are correct @dsyer in that Angular 12 removed Protractor support. I've found that Cypress is a nice alternative. You can see how to integrate Cypress in my Angular Mini-Book. 😊

https://www.infoq.com/minibooks/angular-mini-book/
