### ISSUE TITLE
Upgrade node version

### ISSUE THREAD

**Issue by Tyyagoo** [dsyer/spring-boot-angular#25]
## Issue
The Node version used is very old, it is necessary to update to a newer one.
```xml
<configuration>
    <nodeVersion>v9.11.2</nodeVersion>
</configuration>
```

When running:
```
./ng --version
```

You get:
```
Node.js version v9.11.2 detected.
The Angular CLI requires a minimum Node.js version of either v12.14 or v14.15.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```

## Solution
1. Delete node, node_modules and everything related to node.
2. Update pom.xml:
  ```xml
  <configuration>
      <nodeVersion>v14.18.1</nodeVersion>
  </configuration>
  <!--or choose another compatible version here: https://nodejs.org/dist/-->
  ```
3. Setup everything again.

Note: I don't know if it's an error or a warning because I just deleted the folders and reinstalled using a newer version.

**Comment by dsyer** [comment]
Fixed in main now.
