### ISSUE TITLE
Test backend

### ISSUE THREAD

**Issue by lrkwz** [dsyer/spring-boot-angular#4]
In order to complete your demo I think it sould be better to add `src/main/client/proxy-config.json`

    {
      "/resource": {
        "target": "http://localhost:8080",
        "secure": false
      }
    }

and then modify `src/main/package.json` so that proxy config is used when runnung the `start` script:

      "scripts": {
        "ng": "ng",
        "start": "ng serve --proxy-config proxy-config.json",
        ....

so you can run `src/main/client/yarn start` or `src/main/client/ng serve --proxy-config proxy-config.json`  then start the backend in a new terminal `mvn spring-boot:run` and  access http://localhost:4200 (or either port  the Live Development Server is bound to).

**Comment by dsyer** [comment]
I don't like to use 2 servers where one will suffice. If you read the text in the README it never suggests that you use `./ng serve` at all. I guess it's useful to know how to do it if you want to for some reason, so thanks for the suggestion.
