### ISSUE TITLE
Update Node version in POM file

### ISSUE THREAD

**Issue by rozularen** [dsyer/spring-boot-angular#6]
As of today, Angular CLI v6 requires NodeJS v8.9+ but in the instructions in the README.md, inside the <build> tag you are using v8.8.1 which was causing me problems.

Should change to the latest stable NodeJS version which is v8.11.1

EDIT: Also thanks to another user, the README.md should be updated because the .angular-cli.json file has been renamed to angular.json. Also should update de Angular CLI version to the latest which is v6.0

**Comment by dsyer** [comment]
The sample was written with Angular 4 which worked fine with node 8.8.1. Now on master we have Angular 6 and node 9.11.2.
